// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7umcOeXdRjcXL-4XixCkrFvr8PHIs5M',
    appId: '1:868991271171:android:c7a2e0c2367bd7681be936',
    messagingSenderId: '868991271171',
    projectId: 'cookmate-pcps2025',
    storageBucket: 'cookmate-pcps2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZQmRxzUIEvanh8lC5zy5g2lEhgJe-cmc',
    appId: '1:868991271171:ios:931ee17ab3d7d04c1be936',
    messagingSenderId: '868991271171',
    projectId: 'cookmate-pcps2025',
    storageBucket: 'cookmate-pcps2025.firebasestorage.app',
    iosBundleId: 'com.example.cookmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkkGh4dA4X_6Y_gpHUCYWvgYPUQsesL9M',
    appId: '1:868991271171:web:0f0db9fcb2f8ec691be936',
    messagingSenderId: '868991271171',
    projectId: 'cookmate-pcps2025',
    authDomain: 'cookmate-pcps2025.firebaseapp.com',
    storageBucket: 'cookmate-pcps2025.firebasestorage.app',
    measurementId: 'G-76KLHRFKJ5',
  );
}
